application: departuretimes
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static 

builtins:
- django_wsgi: on

env_variables:
  DJANGO_SETTINGS_MODULE: 'DepartureTimes.settings'
